### ISSUE TITLE
Incorrect Marker?

### ISSUE THREAD

**Issue by irothschild** [MathieuLoutre/mock-aws-s3#12]
It looks like Marker is not being used properly. According the to docs here http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html, the NextMarker in the response should be what you're setting as the Marker, and Marker in the response should be what was passed in with the request.

**Comment by irothschild** [comment]
Added a PR https://github.com/MathieuLoutre/mock-aws-s3/pull/13

**Comment by MathieuLoutre** [comment]
Thanks for the PR! Awesome job!
