### ISSUE TITLE
Bound parameters (default options) are specified differently from real AWS.S3 sdk

### ISSUE THREAD

**Issue by irothschild** [MathieuLoutre/mock-aws-s3#18]
I noticed that the real S3 sdk takes the bound parameters (default options) in the "params" key:

```
var s3bucket = new AWS.S3({ params: {Bucket: 'myBucket'} });
```

(see http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-services.html#Bound_Parameters)

The mock s3 has them at the top level:

```
var s3 = AWSMock.S3({
    Bucket: '/tmp/example'
});
```

**Comment by MathieuLoutre** [comment]
Fixed in #17.
