### ISSUE TITLE
putObject should return an object

### ISSUE THREAD

**Issue by IonicaBizau** [MathieuLoutre/mock-aws-s3#23]
https://github.com/MathieuLoutre/mock-aws-s3/blob/4b247d682b6879d6b9da45b859886a84502fa54f/lib/mock.js#L221-L255

Me and @AllieRays coded  a solution to return an object containing the `send` method, simulating the s3 module. :four_leaf_clover: 

@AllieRays Don't forget to fork, commit, pull request that change, so after `npm install`ing you will not lose it. :joy:

**Comment by MathieuLoutre** [comment]
Sure, happy to take a pull request! Haven't had the time to merge the current one yet, but will hopefully get to do that soon! I saw @AllieRays had a PR going on yesterday but it's been closed.

**Comment by IonicaBizau** [comment]
@MathieuLoutre Addressed in #24. :four_leaf_clover:

**Comment by AllieRays** [comment]
I actually closed the pull request, because I wasn't sure if putObject was suppose to be able to send back an object of "send". Let me reopen the pull request and show you the updated code I did after playing around with it.

Thank you. 

- Allie

**Comment by IonicaBizau** [comment]
@AllieRays I already opened #24 with your change. When you open a PR on GitHub your changes are visible even you close the pull request or delete the branch. :smile:
