### ISSUE TITLE
CreateBucket method

### ISSUE THREAD

**Issue by neilstuartcraig** [MathieuLoutre/mock-aws-s3#27]
Hello

Firstly, thanks for the work you've all put in on this package - I just started using it on a small module i'm writing. I just need 2 methods for my tests, S3.putObject and S3.createBucket - obviously only the former is implemented right now. 

I'm just wanting to ask if you'd consider me contributing a PR to add s3.createBucket. Having looked through the source a little, i have an idea how i'd add it to be compatible with the existing code. I guess the simplest way would be to just create the dir on disk and then perhaps as a second phase, modify e.g. s3.putObject to verify the existence of a bucket before allowing a put (this would also help my use case, incidentally).

Cheers

**Comment by MathieuLoutre** [comment]
Oh I see. Yes, a PR would be very welcome. Always happy to improve the API compatibility if we can. I think a PR to create the bucket and maybe a separate one to make putObject check for existence of the bucket is best (because it would be nice to keep everything backwards compatible if we can). Let me know how you're getting on!

**Comment by neilstuartcraig** [comment]
Sorry for the slow reply @MathieuLoutre - i'll work on this and send one over for your consideration.

Cheets

**Comment by neilstuartcraig** [comment]
Hi again @MathieuLoutre 

I am working on the `createBucket` method at the moment - it's done to a simple level, just adding tests. 

I've noticed that the travis config is only testing node v0.10 and v0.12. Which versions of node do you want to target? I ask because i'd normally use `let`, `const` etc. but will avoid these if you want to continue to target node < current LTS - v4.

Cheers

**Comment by neilstuartcraig** [comment]
Apologies for the separate commits - I can rebase/squash if you prefer

**Comment by neilstuartcraig** [comment]
Sorry, last message. I reverted to older style syntax which should (I hope) allow usage on node v0.10 and v0.12.
I didn't add to the released versions list on the readme doc as i don't want to presume you're happy with the changes.
I'm going to create another couple of issues to discuss some more ideas.
Cheers

**Comment by MathieuLoutre** [comment]
Thanks Neil! That looks good. Good shout on supporting Node 0.10, I think it's safer to stay with at least supporting 0.12 for a little longer. I only had the time to do a quick read but if you had the time to rebase/squash it would make the review faster (although it looks ok on first read). How does that sound?

**Comment by neilstuartcraig** [comment]
Great, thanks @MathieuLoutre - I'll try to get that done this afternoon.

Cheers

**Comment by MathieuLoutre** [comment]
Published in `2.3.0`! Thanks for contributing :)
