### ISSUE TITLE
putObject should pass callback an object

### ISSUE THREAD

**Issue by gabegorelick** [MathieuLoutre/mock-aws-s3#33]
From the [S3 docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property), the second parameter to the `putObject` callback should "the de-serialized data returned from the request. Set to null if a request error occurs." But mock-aws-s3's version isn't passing anything.

**Comment by pamelafox** [comment]
This is what I did on line 342 to achieve that:
`fs.writeFile(dest, search.Body, function (err) {
                                done(err, {Location: dest});
                        });`

**Comment by MathieuLoutre** [comment]
Thanks, just merged that. Sorry it took this long to get a fix...
