### ISSUE TITLE
getObject should answer correctly of object not found

### ISSUE THREAD

**Issue by derPuntigamer** [MathieuLoutre/mock-aws-s3#34]
getObject() on an entry which does not exists results in an "ENOENT" - file not found exception, while the mocked S3 tries to open the object's file without checking its existence. This behavior does not mimic the AWS S3, since S3 sends no error in this scenario, just an object with the answer:

``` json
...
code: "NoSuchKey",
message: "The specified key does not exist.",
name: "NoSuchKey",
region: null,
statusCode: 404
...
```

**Comment by MathieuLoutre** [comment]
Your fix is published in `2.4.0`
