### ISSUE TITLE
S3 Upload with in cucumber.js does not save content.

### ISSUE THREAD

**Issue by r0w4n** [MathieuLoutre/mock-aws-s3#39]
S3 file upload does not work correctly within cucumber.js. The file is created but it does not have any content.

See the attached test cases:

Run node test.js and show that it is working in the normal case.

Run npm test and look for the echoed "content" string within the cucumber message. This should be "content template" but appears as "content" hence no file content - confirm by opening the file within a text editor (C:/projects/test/files/test/test.txt).

[test.zip](https://github.com/MathieuLoutre/mock-aws-s3/files/964571/test.zip)

**Comment by MathieuLoutre** [comment]
Hi there! Sorry, I'm completely unfamiliar with cucumber.js so I'm not sure I can help without some ideas of what could be happening. Thanks for providing a code sample though, that should be useful. I'm not too sure about when I'll be able to look into it, but if you'd like to submit a PR, I'm more than happy!

**Comment by r0w4n** [comment]
I've had another look this "issue" and realised it is my mistake. I'm completely new to using cucumber but this isn't a great excuse. I missed the cucumber call back. My bad.

**Comment by MathieuLoutre** [comment]
No worries! Happens to the best of us!
