### ISSUE TITLE
Missing deleteObject functionality

### ISSUE THREAD

**Issue by petermilan** [MathieuLoutre/mock-aws-s3#4]
Tried to find deleteObject function, but it seems to be removed from the library. There exists only deleteObjects functionality

**Comment by MathieuLoutre** [comment]
Hi there! Indeed, it's only a small subset used by the plugin `grunt-aws-s3`. I'm happy to take a PR if you want to take a stab at it. It should be similar to `deleteObjects` in some ways.

**Comment by MathieuLoutre** [comment]
In fact, that was an error, it's now back in thanks to @lbud!

**Comment by petermilan** [comment]
perfect, thanks.
