### ISSUE TITLE
In v2.5.0, getObject throws error when file is not present in mock bucket 

### ISSUE THREAD

**Issue by AllanHodkinson** [MathieuLoutre/mock-aws-s3#41]
Issue and fix outline here:
https://github.com/MathieuLoutre/mock-aws-s3/pull/38

**Comment by MathieuLoutre** [comment]
Hopefully fixed in 2.5.1. Let me know if not. Thanks!

**Comment by AllanHodkinson** [comment]
Yes it's working now.
Thanks for the quick fix!

**Comment by MathieuLoutre** [comment]
Perfect! Thanks, I'll be more careful next time ;)
