### ISSUE TITLE
Any chance of adding Promises?

### ISSUE THREAD

**Issue by rfink** [MathieuLoutre/mock-aws-s3#42]
The core aws-sdk dependency added promises to the core, via a ".promise" call appended to each service. Ex:

```javascript
  var s3 = new AWS.S3();
  s3.listBuckets(params).promise().then();
```
Any chance of that functionality being added to this library?

**Comment by MathieuLoutre** [comment]
Hello @rfink, only seeing this now sorry. For some reason I'm not getting notifications... Anyway, I guess that would be a nice addition to the library but I'm not a heavy promise user so I'm not fully certain as to how one may go about adding support. If you feel like taking a stab at it, I'd happily review and consider it!

**Comment by kevintechie** [comment]
I am unable to use mock-aws-s3 to test code that uses AWS.S3 promises. You may be able to get hints on how to implement this from the AWS.S3 source code.

**Comment by mysteron** [comment]
@MathieuLoutre to be able to use mock-aws-s3 for tests of the existing code it is necessary to have promise support. Any chance of getting that?

**Comment by MathieuLoutre** [comment]
@mysteron I'd love to and since my last message I've started to use promise/async/await heavily but unfortunately I don't have a lot of time to dedicate to this since I'm not currently using it in any major projects. However, still happy to consider a PR that maintains both styles just like the SDK.

**Comment by mysteron** [comment]
@MathieuLoutre I understand. For my project I've added promise support for three or four functions that I use from mock-aws-s3. I'll consider do it properly for all functions...

**Comment by MathieuLoutre** [comment]
@mysteron that sounds great actually. Have you forked the project? If you put the link here maybe someone can take a look at make a general PR for it if you don't have the time to do it yourself.

**Comment by MathieuLoutre** [comment]
This has been merged now! Let me know how you get on with it.
