### ISSUE TITLE
Promises are not Working for createBucket

### ISSUE THREAD

**Issue by caleblogan** [MathieuLoutre/mock-aws-s3#50]
Running the following code:
```javascript
var AWSMock = require('mock-aws-s3');
AWSMock.config.basePath = './tmp/buckets/' // Can configure a basePath for your local buckets
var s3 = AWSMock.S3({
    params: { Bucket: 'example' }
});

async function test() {
    await s3.createBucket({
        Bucket: "example"
    }).promise()
}

test()
```

throws this error:
```
/home/me/testing/node_modules/mock-aws-s3/lib/mock.js:376
				return callback(err);
				       ^

TypeError: callback is not a function
    at /home/me/testing/node_modules/mock-aws-s3/lib/mock.js:376:12
    at /home/me/testing/node_modules/mkdirp/index.js:38:26
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by MathieuLoutre** [comment]
Do they work for any other of the other methods? I didn't do the implementation myself so I should look into this deeper, but would be good to know how deep this is running.

**Comment by xech3l0nx** [comment]
it doesn't seem to be working with uploadFile either

**Comment by haus** [comment]
also does not seem to work with `listObjects`

**Comment by TheDynomike** [comment]
add listObjectsV2 to the list...

**Comment by joaomilho** [comment]
Doesn't work for `copyObject` as well. I don't have much time to help with a PR, but here's the problem:

Probably whoever implemented this only needed for functions that are triadic like upload: ` upload: function (search, options, callback)`.

The implementation goes:

```js
promise: function () {
  return promisified(search, options);
}
```

This means 2 arguments will be passed to the wrapped function, which is correct when the function is triadic.

Now, when a function is dyadic, like all the ones mentioned above, it should simply do `promisified(search)`.

The simplest fix would be to get the wrapped fn arity and then decide what to pass, like so:

```js
promise: function () {
  switch(wrapped.length) {
    case 2:
      return promisified(search);
    case 3:
      return promisified(search, options);
    default:
      throw new Error('WHaT!?')
  }
}
```

**Comment by MathieuLoutre** [comment]
This should be fixed in v4 now.
