### ISSUE TITLE
When `S3.getObject` not passed with a callback should return the `FakeStream` instead returns a promise

### ISSUE THREAD

**Issue by saswatds** [MathieuLoutre/mock-aws-s3#56]
The promise interface breaks the ability for `getObject` to return a stream when not provided with a callback. Same is the case for `headObject`.

One more suggestion- You might also want to export the `S3Mock` for consumers to override certain behaviours if required.

**Comment by shb** [comment]
It seems that this was implemented as soon as version 0.2.0 back in the 2014, but then it broke when the promise interface was added, as no tests was devised for the scenario.

I published a PR (#60) to fix this and add a proper test.
