### ISSUE TITLE
AssertionError when trying to remove a folder (using deleteBucket)

### ISSUE THREAD

**Issue by ouam** [MathieuLoutre/mock-aws-s3#61]
While using the deleteBucket function, I get the following error:
  
```javascript
AssertionError [ERR_ASSERTION]: false == true
    at rmdir (/media/sylvain/Store/projects/devpipeline/services/AmbraIngestionServer/node_modules/fs-extra/node_modules/rimraf/rimraf.js:159:5)
    at /media/sylvain/Store/projects/devpipeline/services/AmbraIngestionServer/node_modules/fs-extra/node_modules/rimraf/rimraf.js:97:16
    at FSReqWrap.oncomplete (fs.js:135:15)
```

After some research on google, it looks like it is caused by the package rimraf not being up to date.
The rimraf package is included in the fs-extra package (also out of date) which mock-aws-s3 includes.

I have confirmed the error no longer occurs after updating fs-extra from 0.6.4 to 7.0.1 but I don't know what impact updating fs-extra could have on other functions.

**Comment by MathieuLoutre** [comment]
Just merged @TastefulElk's PR and pushed 4.0.1 which should fix it. Thanks for reporting!
