### ISSUE TITLE
need to upgrade underscore pkg version from 1.8.3 to 1.12.1 to fix critical vulnerability.

### ISSUE THREAD

**Issue by ravi-soda** [MathieuLoutre/mock-aws-s3#79]
mock-aws-s3 is using the underscore pkg version #1.8.3 which is having a critical vulnerability. Can you please upgrade the underscore pkg version to 1.12.* or above. Please let us know ASAP.

**Comment by ravi-soda** [comment]
Seems like there is a PullRequest already created for this, please approve the [Pull Request](https://github.com/MathieuLoutre/mock-aws-s3/pull/77)

**Comment by MathieuLoutre** [comment]
Published v4.0.2 with a bunch of package updates. Let me know if that works for you.
